config/routes.rb
Aszist::Application.routes.draw do

  devise_for :users

  resources :tickets do
    resources :comments
  end

  resources :users, except: [ :show ] do
    collection do
      post 'manage'
    end
  end

  get "/profile", to: "profiles#edit", as: :edit_profile
  patch "/profile", to: "profiles#update"

  root :to => 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :agent, :class_name => "User"
  has_many :comments

  accepts_nested_attributes_for :comments

  has_paper_trail

  STATUSES = %w( pending open closed )
  PRIORITIES = %w( low medium high )

  validates :user_id, :presence => true
  validates :status, :inclusion => { :in => Ticket::STATUSES }
  validates :priority, :inclusion => { :in => Ticket::PRIORITIES }
  validates :token, :presence => true, :uniqueness => true

  after_initialize :generate_token

  before_validation :set_pending,
                    :set_default_priority,
                    :create_user,


  def activity
    (comments + versions).sort_by(&:created_at)
  end

  def self.actionable
    where("status = 'pending' OR status = 'open'")
  end

  def self.newest_first
    order("created_at DESC")
  end

  def self.pending_tickets
    where(status: "pending")
  end

  def self.open_tickets
    where(status: "open")
  end

  def self.closed_tickets
    where(status: "closed")
  end

  def self.low_priority
    where(priority: "low")
  end

  def self.medium_priority
    where(priority: "medium")
  end

  def self.high_priority
    where(priority: "high")
  end

  def self.visible(user)
    if user.role?(:admin)
      all
    else
      where("user_id = ? OR agent_id = ?", user.id, user.id)
    end
  end

  # Will not return an ActiveRecord::Relation!
  def self.group_by_status
    all.group_by(&:status)
  end

  protected

  def set_pending
    self.status = STATUSES.first if self.status.blank?
  end

  def set_default_priority
    self.priority = PRIORITIES.first if self.priority.blank?
  end

  def create_user
    if self.user.blank?
      # TODO: Create new user for email and assign to ticket
    end
  end

  def generate_token
    self.token ||= SecureRandom.hex(8)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!
  # check_authorization

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.newest_first.visible(current_user).group_by_status

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    @ticket.user = current_user if @ticket.user.nil?
    @ticket.agent = User.default_agent if @ticket.agent.nil?

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :ok }
    end
  end

  protected

  def ticket_params
    params.require(:ticket).permit(:user_id, :agent_id, :priority, :status, :subject, :body)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_comment.html.haml
%div.panel{ class: ("callout" if comment.sent_to_user?) }
  %p
    %strong= comment.user
    = raw("<em>(Sent to user)</em>") if comment.sent_to_user?
    = time_ago_in_words(comment.created_at).humanize
    ago
  %p
    = markdownify comment.body

app/views/tickets/_form.html.haml
= simple_form_for(@ticket) do |f|
  = f.error_notification

  .inputs
    - if can? :manage, @ticket
      = f.input :agent_id, :collection => User.agents.collect{|a| [a.name, a.id]}, :prompt => false
      = f.input :status, :collection => Ticket::STATUSES.collect{|s| [s.humanize, s] }, :prompt => false
      = f.input :priority, :collection => Ticket::PRIORITIES.collect{|p| [p.humanize, p] }, :prompt => false
    = f.input :subject
    = f.input :body, input_html: { rows: 8 }

    .actions
      = f.submit class: "button"

app/views/tickets/_version.html.haml
- @user = User.where(id: version.whodunnit).first

- version.changeset.slice(:priority, :status, :subject, :body).each do |attribute, values|
  .alert-box.round.secondary
    %strong= @user
    changed the
    %strong= attribute
    from
    %strong= values.first
    to
    %strong= values.last
    %em.label.success.round
      = time_ago_in_words(version.created_at).humanize
      ago

app/views/tickets/edit.html.haml
%ul.breadcrumbs
  %li= link_to "Tickets", tickets_path
  %li= link_to @ticket.id, @ticket
  %li Edit

%h1 Editing ticket

= render 'form'

app/views/tickets/index.html.haml
%p.right= link_to 'New Ticket', new_ticket_path, class: "small round success button"

%h2 Your tickets
- Ticket::STATUSES.each do |status|
  %div{:class => "group #{status}"}
    %h4
      = status.humanize
      tickets
    - if @tickets[status].blank?
      %p.alert-box.secondary
        No #{status} tickets.
    - else
      %table.small-12
        %thead
          %tr
            %th ID
            %th Date
            %th Subject
            %th Priority
        - tickets = @tickets[status].group_by(&:priority)
        - Ticket::PRIORITIES.reverse.each do |priority|
          - unless tickets[priority].to_s.empty?
            - tickets[priority].each do |ticket|
              %tr{:class => "#{ticket.priority} #{ticket.status}", :id => "ticket-#{ticket.id}"}
                %td.id= link_to ticket.id, ticket
                %td.date
                  = time_ago_in_words(ticket.created_at).humanize
                  ago
                %td.subject= link_to ticket.subject, url_for(ticket)
                %td{:class => "priority #{ticket.priority}"}= ticket.priority.humanize

app/views/tickets/new.html.haml
%ul.breadcrumbs
  %li= link_to "Tickets", tickets_path
  %li New Ticket

%h1 New ticket

= render 'form'

app/views/tickets/show.html.haml
%ul.breadcrumbs
  %li= link_to "Tickets", tickets_path
  %li= @ticket.id

%h1 Ticket ##{@ticket.id}

%table.small-12.medium-6
  %tr
    %th{ scope: "row"} From:
    %td= @ticket.user
  %tr
    %th{ scope: "row" } Assigned to:
    %td
      = @ticket.agent
      (#{link_to "Change", edit_ticket_path(@ticket)})
  %tr
    %th{ scope: "row" } Status:
    %td
      = @ticket.status.humanize
      (#{link_to "Change", edit_ticket_path(@ticket)})
  %tr
    %th{ scope: "row" } Priority:
    %td
      = @ticket.priority.humanize
      (#{link_to "Change", edit_ticket_path(@ticket)})
  %tr
    %th{ scope: "row" } Subject:
    %td
      = @ticket.subject

= markdownify @ticket.body

%hr/

%h3 Comments
- @ticket.activity.each do |activity|
  - if activity.class.to_s == "Comment"
    = render "tickets/comment", comment: activity
  - else
    = render "tickets/version", version: activity

%h4 Add a new comment
= simple_form_for [@ticket, @comment] do |f|
  %p= f.input :body, input_html: { rows: 5 }
  %p
    %em Processed with Markdown
  - if current_user.role?(:agent)
    %p= f.input :sent_to_user, label: "Send email notification"

  %p= f.submit "Add Comment", class: "button"